name: smartattend_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  responsive_sizer: ^3.3.1
  riverpod_annotation: ^2.3.5
  video_player: 
  socket_io_client: ^2.0.3+1
  flutter_background_service: ^5.0.6
  awesome_notifications_core: ^0.9.0 
  awesome_notifications: any
  flutter_local_notifications: ^17.2.1+1
  get_it: ^7.7.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: 
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_native_splash: 

# native splash screen for android and ios
flutter_native_splash:
  color: "#e43e3a"
  android: true
  ios: true
  image: lib/global/assets/background1.png

  
  android_12:
    color: "#e43e3a"
    image: lib/global/assets/background1.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/global/assets/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: lib/global/fonts/Segoe UI.ttf
        - asset: lib/global/fonts/Segoe UI Bold.ttf
          weight: 700